version: '2'

services:
  telegraf:
    build:
      context: .
      dockerfile: telegraf.Dockerfile
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  influxdb:
    build:
      context: .
      dockerfile: influxdb.Dockerfile
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
