version: '2'

services:
  telegraf:
    build:
      context: .
      dockerfile: telegraf.Dockerfile
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  influxdb:
    build:
      context: .
      dockerfile: influxdb.Dockerfile
    volumes:
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
